# Generated by Django 3.2.9 on 2021-12-14 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutmebody', mdeditor.fields.MDTextField(verbose_name='个人介绍')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '个人介绍',
                'verbose_name_plural': '个人介绍',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminTitle', models.CharField(max_length=200, verbose_name='标题')),
                ('AdminAvatarsImg', models.ImageField(upload_to='author/', verbose_name='首页作者图片(800*800)')),
                ('AdminAvatarsImgAlt', models.CharField(max_length=2000, verbose_name='首页作者图片描述')),
                ('AdminProfile', models.TextField(verbose_name='首页作者描述')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
        migrations.CreateModel(
            name='ArticleSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SortTitle', models.CharField(max_length=200, verbose_name='文章分类')),
                ('SortCreate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='分类创建时间')),
                ('SortTitle_T', models.CharField(default='', max_length=200, verbose_name='优化标题')),
                ('SortTitle_D', models.CharField(default='', max_length=200, verbose_name='优化描述')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BannerTitle', models.CharField(default='', max_length=200, verbose_name='轮播图标题')),
                ('BannerDes', models.CharField(default='', max_length=200, verbose_name='轮播图描述')),
                ('BannerUrl', models.ImageField(upload_to='banner/', verbose_name='轮播图链接(1400*800)')),
                ('ImgAlt', models.CharField(default='', max_length=200, verbose_name='轮播图alt')),
            ],
            options={
                'verbose_name': '主轮播图',
                'verbose_name_plural': '主轮播图',
            },
        ),
        migrations.CreateModel(
            name='IndexSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IndexSeotTitle', models.CharField(max_length=200, verbose_name='首页标题')),
                ('IndexSeoDes', models.TextField(verbose_name='首页描述')),
            ],
            options={
                'verbose_name': '首页TDK',
                'verbose_name_plural': '首页TDK',
            },
        ),
        migrations.CreateModel(
            name='LinkFri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LinkName', models.CharField(max_length=200, verbose_name='链接名称')),
                ('LinkUrl', models.URLField(verbose_name='友情链接')),
                ('LinkCreate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='链接创建时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否显示')),
                ('LinkRel', models.CharField(default='', max_length=200, verbose_name='链接是否抓取')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='SpecintroDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecintroTitle', models.CharField(max_length=200, verbose_name='技能标题')),
                ('Specintro', models.TextField(verbose_name='技能介绍')),
            ],
            options={
                'verbose_name': '特别技能',
                'verbose_name_plural': '特别技能',
            },
        ),
        migrations.CreateModel(
            name='ArticlePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('meDes', models.TextField(max_length=300, verbose_name='文章描述')),
                ('asBody', mdeditor.fields.MDTextField(verbose_name='文本内容')),
                ('poTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('upTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('arImg', models.ImageField(blank=True, upload_to='article/%Y%m%d/', verbose_name='文章缩略图(740*400)')),
                ('arImgAlt', models.CharField(blank=True, max_length=200, verbose_name='缩略图描述')),
                ('total_view', models.PositiveIntegerField(default=0, verbose_name='文章浏览数')),
                ('arSort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articlesort', verbose_name='分类')),
                ('arTags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='文章标签')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='文章作者')),
            ],
            options={
                'verbose_name': '文章内容',
                'verbose_name_plural': '文章内容',
                'ordering': ('-id',),
            },
        ),
    ]
